In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
matrix = np.random.rand(5, 5)

In [3]:
print (matrix)

[[0.7852914  0.65049614 0.91480158 0.90412532 0.51904882]
 [0.18864471 0.12950717 0.30428549 0.89223234 0.17479159]
 [0.50752574 0.35678054 0.11327694 0.42603522 0.18869059]
 [0.54540082 0.85822663 0.95378087 0.73973158 0.00251042]
 [0.43880498 0.77203834 0.59562541 0.46262978 0.73725539]]


In [4]:
row_min = np.min(matrix, axis=1)
row_max = np.max(matrix, axis=1)

col_min = np.min(matrix, axis=0)
col_max = np.max(matrix, axis=0)

In [5]:
print("Minimum values along each row:", row_min)
print("Maximum values along each row:", row_max)
print("Minimum values along each column:", col_min)
print("Maximum values along each column:", col_max)

Minimum values along each row: [0.51904882 0.12950717 0.11327694 0.00251042 0.43880498]
Maximum values along each row: [0.91480158 0.89223234 0.50752574 0.95378087 0.77203834]
Minimum values along each column: [0.18864471 0.12950717 0.11327694 0.42603522 0.00251042]
Maximum values along each column: [0.7852914  0.85822663 0.95378087 0.90412532 0.73725539]


In [6]:
def generate_matrix(rows, cols):
  matrix = []
  for i in range(rows):
    row = []
    for j in range(cols):
      value = float(input(f"Enter element for row {i+1}, column {j+1}: "))
      row.append(value)
    matrix.append(row)
  return matrix

def find_min_max_row(matrix):
  row_min = []
  row_max = []
  for row in matrix:
    min_value = row[0]
    max_value = row[0]
    for value in row:
      min_value = min(min_value, value)
      max_value = max(max_value, value)
    row_min.append(min_value)
    row_max.append(max_value)
  return row_min, row_max

def find_min_max_col(matrix):
  cols = len(matrix[0])
  col_min = [float('inf')] * cols
  col_max = [float('-inf')] * cols
  for row in matrix:
    for i in range(cols):
      col_min[i] = min(col_min[i], row[i])
      col_max[i] = max(col_max[i], row[i])
  return col_min, col_max

rows = int(input("Enter the number of rows: "))
cols = int(input("Enter the number of columns: "))

matrix = generate_matrix(rows, cols)

row_min, row_max = find_min_max_row(matrix)
col_min, col_max = find_min_max_col(matrix)

print("Minimum values along each row:", row_min)
print("Maximum values along each row:", row_max)
print("Minimum values along each column:", col_min)
print("Maximum values along each column:", col_max)


Enter the number of rows:  5
Enter the number of columns:  5
Enter element for row 1, column 1:  3
Enter element for row 1, column 2:  2
Enter element for row 1, column 3:  5
Enter element for row 1, column 4:  6
Enter element for row 1, column 5:  7
Enter element for row 2, column 1:  1
Enter element for row 2, column 2:  2
Enter element for row 2, column 3:  3
Enter element for row 2, column 4:  4
Enter element for row 2, column 5:  5
Enter element for row 3, column 1:  9
Enter element for row 3, column 2:  8
Enter element for row 3, column 3:  7
Enter element for row 3, column 4:  6
Enter element for row 3, column 5:  5
Enter element for row 4, column 1:  7
Enter element for row 4, column 2:  4
Enter element for row 4, column 3:  5
Enter element for row 4, column 4:  2
Enter element for row 4, column 5:  1
Enter element for row 5, column 1:  0
Enter element for row 5, column 2:  5
Enter element for row 5, column 3:  6
Enter element for row 5, column 4:  0
Enter element for row 5, co

Minimum values along each row: [2.0, 1.0, 5.0, 1.0, 0.0]
Maximum values along each row: [7.0, 5.0, 9.0, 7.0, 9.0]
Minimum values along each column: [0.0, 2.0, 3.0, 0.0, 1.0]
Maximum values along each column: [9.0, 8.0, 7.0, 6.0, 9.0]
